nginx:
    build: ./nginx
    ports:
      - "80:80"
    links:
      - "php"
    volumes:
      - /home/han/opt:/opt
    container_name: nginx

php:
    build: ./php
    ports:
      - "9000:9000"
    links:
      - "mysql"
      - "redis"
      - "elasticsearch"
    volumes:
      - /home/han/opt:/opt
    container_name: php

mysql:
    build: ./mysql
    ports:
      - "3306:3306"
    volumes:
      - /home/han/opt/data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    container_name: mysql

redis:
    build: ./redis
    ports:
      - "6379:6379"
    container_name: redis

elasticsearch:
    build: ./elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    container_name: elasticsearch
        
phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: myadmin
    environment:
        - PMA_ARBITRARY=1
        - PMA_HOST=mysql
    restart: always
    ports:
        - "8080:8080"
    links:
        - "mysql"
smzdm_crawler:
    build: ./smzdm_crawler
    volumes:
      - /home/han/opt/python:/usr/src/app
    links:
      - "mysql"
    container_name: smcrawler

